# This is a basic workflow to help you get started with Actions

name: Run script on push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  run-script-push:
    name: Run script on push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run script to print foo
        run: |
          sh ./.github/workflows/scripts/test.sh
