# This is a basic workflow to help you get started with Actions

name: Run script

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

jobs:
  run-script:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run script to print foo
        shell: bash
        run: |
          sh ./.github/workflows/scripts/test.sh
          sh ./.github/workflows/scripts/files_changed.sh
